### ISSUE TITLE
Example broken by custom keywords

### ISSUE THREAD

**Issue by FabienRoger** [bangawayoo/nlp-watermarking#2]
When running `scripts/example/run-imdb.sh` I get the following stack trace:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ubuntu/nlp-watermarking/./ours.py:37 in <module>                                           │
│                                                                                                  │
│    34 spacy_tokenizer = spacy.load(generic_args.spacy_model)                                     │
│    35 if "trf" in generic_args.spacy_model:                                                      │
│    36 │   spacy.require_gpu()                                                                    │
│ ❱  37 model = InfillModel(infill_args, dirname=dirname)                                          │
│    38                                                                                            │
│    39 _, cover_texts = model.return_dataset()                                                    │
│    40                                                                                            │
│                                                                                                  │
│ /home/ubuntu/nlp-watermarking/models/watermark.py:70 in __init__                                 │
│                                                                                                  │
│    67 │   │   │   │   │   │   │   │   │   │     mask_order_by=args.mask_order_by,                │
│    68 │   │   │   │   │   │   │   │   │   │     keyword_mask=args.keyword_mask,                  │
│    69 │   │   │   │   │   │   │   │   │   │     exclude_cc=args.exclude_cc,                      │
│ ❱  70 │   │   │   │   │   │   │   │   │   │     custom_keywords=args.custom_keywords             │
│    71 │   │   │   │   │   │   │   │   │   │     )                                                │
│    72 │   │   self.nlp = spacy.load(args.spacy_model)                                            │
│    73                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'custom_keywords'
```

**Comment by bangawayoo** [comment]
Hi,
The custom keyword functionality was only used for demo.py in case anyone wanted to exclude any keywords or proper nouns that are not detected by the spacy model.

If you'd like to use for imdb as well, just add this [line](https://github.com/bangawayoo/nlp-watermarking/blob/74fecb898a81b953c9837764ad65e34653c8e8d5/demo.py#L47C1-L47C60) in `ours.py`.
The InfillModel will handle it afterwards and exclude it from being masked out. 

Hope this helps!

**Comment by bangawayoo** [comment]
Hi @FabienRoger 
I am closing the issue due to inactivity.
Feel free to open it if there is another issue.

**Comment by awaylong** [comment]
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "F:\Robust_watermarking\nlp-watermarking\context-ls.py", line 108, in <module>
    raise AssertionError("Mode should be specified")
AssertionError: Mode should be specified
//what happened？
